const fs = require('fs');
const path = require('path');

// Read .env.prod from parent directory
const envProdPath = path.join(__dirname, '..', '..', '.env.prod');
const envContent = fs.readFileSync(envProdPath, 'utf8');

// Extract SSROK_SERVER
const serverUrlMatch = envContent.match(/^SSROK_SERVER=(.+)$/m);
let serverUrl = serverUrlMatch ? serverUrlMatch[1].trim() : 'http://localhost';

// Trim trailing slash to avoid double slashes
serverUrl = serverUrl.replace(/\/$/, '');

// Generate config file
const configContent = `// Auto-generated by build script - DO NOT EDIT
export const SSROK_SERVER = '${serverUrl}';
`;

const configPath = path.join(__dirname, '..', 'src', 'config.ts');
fs.writeFileSync(configPath, configContent);

console.log(`Build config generated: SSROK_SERVER=${serverUrl}`);
